### ISSUE TITLE
Peer-Peer Review Capstone1

### ISSUE THREAD

**Issue by Somdotta07** [cwaku/capstone-project#3]
Good job so far with your code! 👏 

It's looking pretty good, but there are a few changes you should make in order to make it look even better 🤓 .

- In the **nav-bar**, the logo should be placed on the left of the nav-bar
- Fix the **hr** for the desktop
- Program heading (mobile version) change from di**splay: none** to **text-align: center**
- Change the footer color to dark given in the template

**Comment by karelvanoordt** [comment]
Nice job with your project so far! 😎 

You are almost done! But first I think you should consider these changes to make your code a little bit better.

-- Don't forget to add descriptive `alt` text to your images and icons to improve accessibility.
